version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build:
    docker:
    - image: cimg/node:12.16.0-browsers
    steps:
    - checkout
    - run: npm install
    - browser-tools/install-chrome
    - browser-tools/install-chromedriver
    - run:
        command: |
          google-chrome --version
          chromedriver --version
        name: Check install
    - run: npm start
workflows:
  workflow:
    jobs:
    - build
