version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build:
    docker:
    - image: cypress/included
    steps:
    - checkout
    # - run: npm install
    # - browser-tools/install-chrome
    # - browser-tools/install-chromedriver
    - run:
        command: |
          google-chrome --version
          # chromedriver --version
        name: Check install
    - run: 
        command: npm start
        background: true
    - run: npx cypress run --spec "./integration/kata_first_test.js"
workflows:
  workflow:
    jobs:
    - build
