version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build:
    docker:
    - image: cimg/node:12.16.0
    # - image: cypress/included
    steps:
    - checkout
    # - run: apt-get update && apt-get install -y curl
    # - run:
    #       name: Install nvm and switch Node.js version
    #       command: |
    #         curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    #         export NVM_DIR="$HOME/.nvm"
    #         [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    #         nvm install 12.16.0 # Specify the Node.js version you want to install
    #         nvm use 12.16.0
    #         node --version
    - run: npm install
    - browser-tools/install-chrome
    - browser-tools/install-chromedriver
    - run:
        command: |
          google-chrome --version
          # chromedriver --version
        name: Check install
    - run: 
        command: npm:start
        background: true
    - run: npx cypress run --spec "./integration/kata_first_test.js"
workflows:
  workflow:
    jobs:
    - build
